version: 2
jobs:
  build:
    context:
      - cd-app
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Docker image"
          command: |
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_LOGIN --password-stdin
            docker build -t kyaary/cd-app .
            docker push kyaary/cd-app
workflows:
  version: 2
  build:
    jobs:
      - build